/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.presentation;

import com.mycompany.Infraestructure.Models.CiudadesModels;
import com.mycompany.Services.CiudadesService;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static javax.swing.UIManager.getInt;

/**
 *
 * @author solua
 */
public class ConsultarCiudad extends javax.swing.JFrame {
   private CiudadesService ciudadesService;
    /**
     * Creates new form Ciudad
     */
    public ConsultarCiudad() {
        initComponents();
         this.setLocationRelativeTo(null);
        ciudadesService = new CiudadesService("postgres", "1234", "localhost", "5432", "postgres");
    }
    private void ConsultarCiudad(String id) {
        cargarDatos(ciudadesService.consultarCiudad(Integer.parseInt(id)));
        
    }
    
    private void nuevaCiudad() {
        CiudadesModels model = new CiudadesModels();
        model.setId(Integer.parseInt(txtIdCiudad.getText()));
        model.setCiudad(txtNombreCiudad.getText());
        model.setDepartamento(txtDepartamento.getText());
        model.setPostal(txtPostal.getText());

        /*txtNombreCiudad.setText(model.nombreCiudad);
        txtDepartamento.setText(model.Departamento);
        txtPostal.setText(model.Postal);*/
        
        String result = ciudadesService.registrarCiudad(model);
        JOptionPane.showMessageDialog(this, result);

        limpiarDatos();
    }
    
    private void cargarDatos(CiudadesModels model){
        if (model!=null){
            txtNombreCiudad.setText(model.getCiudad());
            txtDepartamento.setText(model.getDepartamento());
            txtPostal.setText(model.getPostal());
        }else{
            limpiarDatos();
            JOptionPane.showMessageDialog(this, "No se encontró Ciudad con el id ingresado");
        }
    }
    
    private void limpiarDatos() {
        txtIdCiudad.setText("");
        txtNombreCiudad.setText("");
        txtDepartamento.setText("");
        txtPostal.setText("");
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtDepartamento = new javax.swing.JTextField();
        btnModelBuscarCiudades = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtPostal = new javax.swing.JTextField();
        etiquetaCiudad = new javax.swing.JLabel();
        txtIdCiudad = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtNombreCiudad = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Cancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tituloPrincipal1 = new javax.swing.JLabel();
        btnNew = new javax.swing.JButton();
        Cancelar1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDepartamento.setEnabled(false);

        btnModelBuscarCiudades.setBackground(new java.awt.Color(204, 204, 255));
        btnModelBuscarCiudades.setText("Buscar");
        btnModelBuscarCiudades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModelBuscarCiudadesActionPerformed(evt);
            }
        });

        jLabel4.setText("Postal");

        txtPostal.setEnabled(false);
        txtPostal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPostalKeyPressed(evt);
            }
        });

        etiquetaCiudad.setText("Id Ciudad");

        txtIdCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtIdCiudadKeyPressed(evt);
            }
        });

        jLabel1.setText("Nombre");

        txtNombreCiudad.setEnabled(false);

        jLabel2.setText("Departamento");

        Cancelar.setBackground(new java.awt.Color(204, 204, 0));
        Cancelar.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar.setText("Limpiar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(0, 102, 0));
        btnGuardar.setForeground(new java.awt.Color(255, 255, 255));
        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 204, 255));
        jPanel1.setForeground(new java.awt.Color(255, 204, 255));

        tituloPrincipal1.setFont(new java.awt.Font("Viner Hand ITC", 1, 24)); // NOI18N
        tituloPrincipal1.setForeground(new java.awt.Color(102, 0, 102));
        tituloPrincipal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloPrincipal1.setText("Ciudades");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addComponent(tituloPrincipal1, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                .addGap(123, 123, 123))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(tituloPrincipal1)
                .addGap(16, 16, 16))
        );

        btnNew.setBackground(new java.awt.Color(204, 204, 255));
        btnNew.setText("Nuevo");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        Cancelar1.setBackground(new java.awt.Color(204, 51, 0));
        Cancelar1.setForeground(new java.awt.Color(255, 255, 255));
        Cancelar1.setText("Salir");
        Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancelar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnNew)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnGuardar)
                                .addGap(18, 18, 18)
                                .addComponent(Cancelar)
                                .addGap(18, 18, 18)
                                .addComponent(Cancelar1)
                                .addGap(38, 38, 38)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(etiquetaCiudad))
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtPostal)
                                .addGap(27, 27, 27))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtDepartamento)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNombreCiudad)
                                .addContainerGap())
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtIdCiudad)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnModelBuscarCiudades)
                                .addContainerGap())))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jSeparator1)
                    .addGap(25, 25, 25)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(etiquetaCiudad, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtIdCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnModelBuscarCiudades, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtPostal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(Cancelar)
                    .addComponent(btnNew)
                    .addComponent(Cancelar1))
                .addGap(25, 25, 25))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(266, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnModelBuscarCiudadesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModelBuscarCiudadesActionPerformed
        ConsultarCiudad(txtIdCiudad.getText());
    }//GEN-LAST:event_btnModelBuscarCiudadesActionPerformed

    private void txtPostalKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPostalKeyPressed
       
    }//GEN-LAST:event_txtPostalKeyPressed

    private void txtIdCiudadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIdCiudadKeyPressed
    }//GEN-LAST:event_txtIdCiudadKeyPressed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        limpiarDatos();
    }//GEN-LAST:event_CancelarActionPerformed

    private void Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancelar1ActionPerformed
         this.setVisible (false);

    }//GEN-LAST:event_Cancelar1ActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        nuevaCiudad();
    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        limpiarDatos();
        txtIdCiudad.setEnabled(true);
        txtNombreCiudad.setEnabled(true);
        txtDepartamento.setEnabled(true);
        txtPostal.setEnabled(true);
    }//GEN-LAST:event_btnNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ConsultarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ConsultarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ConsultarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ConsultarCiudad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ConsultarCiudad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Cancelar1;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnModelBuscarCiudades;
    private javax.swing.JButton btnNew;
    private javax.swing.JLabel etiquetaCiudad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel tituloPrincipal1;
    private javax.swing.JTextField txtDepartamento;
    private javax.swing.JTextField txtIdCiudad;
    private javax.swing.JTextField txtNombreCiudad;
    private javax.swing.JTextField txtPostal;
    // End of variables declaration//GEN-END:variables


   

   
}
